import { yupResolver } from '@hookform/resolvers/yup'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { FiArrowRight, FiEye, FiEyeOff, FiUploadCloud } from 'react-icons/fi'
import { Link, useNavigate } from 'react-router-dom'
import { toast } from 'react-toastify'
import * as yup from 'yup'
import { AuthShell, Field } from '../Login'
import useAuth from '../../hooks/useAuth'
import { apiErrorMessage, roleDashboardPath } from '../../utils/helpers'
import { LoadingSpinner } from '../../components/UI'

const schema = yup.object({ name: yup.string().trim().min(2, 'Enter your full name.').required('Name is required.'), email: yup.string().email('Enter a valid email address.').required('Email is required.'), phone: yup.string().matches(/^[+\d][\d\s-]{6,17}$/, 'Enter a valid mobile number.').required('Mobile number is required.'), password: yup.string().min(8, 'Use at least 8 characters.').matches(/[A-Z]/, 'Include an uppercase letter.').matches(/[a-z]/, 'Include a lowercase letter.').matches(/\d/, 'Include a number.').required('Password is required.'), confirmPassword: yup.string().oneOf([yup.ref('password')], 'Passwords do not match.').required('Please confirm your password.'), role: yup.string().oneOf(['admin', 'doctor', 'receptionist', 'patient']).required('Role is required.'), gender: yup.string().required('Gender is required.'), dob: yup.string().required('Date of birth is required.'), address: yup.string().trim().min(5, 'Enter your address.').required('Address is required.'), profileImage: yup.mixed().test('size', 'Image must be smaller than 3 MB.', (files) => !files?.[0] || files[0].size <= 3 * 1024 * 1024).test('type', 'Use a JPG, PNG, or WEBP image.', (files) => !files?.[0] || ['image/jpeg', 'image/png', 'image/webp'].includes(files[0].type)) })

function Register() {
  const [showPassword, setShowPassword] = useState(false); const { register: registerUser } = useAuth(); const navigate = useNavigate()
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: yupResolver(schema), defaultValues: { role: 'patient', gender: '' } })
  const onSubmit = async ({ profileImage, ...values }) => { const formData = new FormData(); Object.entries(values).forEach(([key, value]) => formData.append(key, value)); if (profileImage?.[0]) formData.append('profileImage', profileImage[0]); try { const user = await registerUser(formData); toast.success('Account created. Please check your email to verify it.'); navigate(roleDashboardPath(user.role), { replace: true }) } catch (error) { toast.error(apiErrorMessage(error, 'Unable to create your account.')) } }
  return <AuthShell title="Create your account" subtitle="Join MediSphere and bring your care experience together."><form className="auth-form register-form" onSubmit={handleSubmit(onSubmit)} noValidate><div className="auth-two-columns"><Field label="Full name" error={errors.name?.message}><input placeholder="Himesh Darji" autoComplete="name" {...register('name')} /></Field><Field label="Mobile number" error={errors.phone?.message}><input placeholder="+91 98765 43210" autoComplete="tel" {...register('phone')} /></Field></div><Field label="Email address" error={errors.email?.message}><input type="email" placeholder="you@hospital.com" autoComplete="email" {...register('email')} /></Field><div className="auth-two-columns"><label className={`role-field ${errors.role ? 'has-error' : ''}`}>Your role<select {...register('role')}><option value="patient">Patient</option><option value="doctor">Doctor</option><option value="receptionist">Receptionist</option><option value="admin">Administrator</option></select>{errors.role && <small>{errors.role.message}</small>}</label><label className={`role-field ${errors.gender ? 'has-error' : ''}`}>Gender<select {...register('gender')}><option value="">Select</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option><option value="prefer-not-to-say">Prefer not to say</option></select>{errors.gender && <small>{errors.gender.message}</small>}</label></div><div className="auth-two-columns"><Field label="Date of birth" error={errors.dob?.message}><input type="date" {...register('dob')} /></Field><label className={`upload-field ${errors.profileImage ? 'has-error' : ''}`}>Profile image <span><FiUploadCloud /> Optional image<input type="file" accept="image/png,image/jpeg,image/webp" {...register('profileImage')} /></span>{errors.profileImage && <small>{errors.profileImage.message}</small>}</label></div><Field label="Address" error={errors.address?.message}><input placeholder="Your address" autoComplete="street-address" {...register('address')} /></Field><div className="auth-two-columns"><Field label="Password" error={errors.password?.message}><input type={showPassword ? 'text' : 'password'} placeholder="Create a strong password" autoComplete="new-password" {...register('password')} /><button className="password-toggle" type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <FiEyeOff /> : <FiEye />}</button></Field><Field label="Confirm password" error={errors.confirmPassword?.message}><input type={showPassword ? 'text' : 'password'} placeholder="Repeat password" autoComplete="new-password" {...register('confirmPassword')} /></Field></div><button className="button auth-submit" type="submit" disabled={isSubmitting}>{isSubmitting ? <LoadingSpinner label="Creating account" /> : <>Create secure account <FiArrowRight /></>}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell>
}
export default Register
