const path = require('path');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const express = require('express');
const helmet = require('helmet');
const morgan = require('morgan');
const authRoutes = require('./routes/authRoutes');
const patientRoutes = require('./routes/patientRoutes');
const doctorRoutes = require('./routes/doctorRoutes');
const appointmentRoutes = require('./routes/appointmentRoutes');
const billingRoutes = require('./routes/billingRoutes');
const laboratoryRoutes = require('./routes/laboratoryRoutes');
const inventoryRoutes = require('./routes/inventoryRoutes');
const departmentRoutes = require('./routes/departmentRoutes');
const dashboardRoutes = require('./routes/dashboardRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const reportRoutes = require('./routes/reportRoutes');
const staffRoutes = require('./routes/staffRoutes');
const clinicalRoutes = require('./routes/clinicalRoutes');
const contactRoutes = require('./routes/contactRoutes');
const { errorHandler, notFound } = require('./middleware/errorMiddleware');

const app = express();
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.get('/api/v1/health', (req, res) => res.json({ success: true, message: 'MediSphere API is healthy.' }));
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/admin/dashboard', dashboardRoutes);
app.use('/api/v1/admin/patients', patientRoutes);
app.use('/api/v1/admin/doctors', doctorRoutes);
app.use('/api/v1/admin/appointments', appointmentRoutes);
app.use('/api/v1/admin/departments', departmentRoutes);
app.use('/api/v1/admin/laboratory', laboratoryRoutes);
app.use('/api/v1/admin/billing', billingRoutes);
app.use('/api/v1/admin/inventory', inventoryRoutes);
app.use('/api/v1/admin/staff', staffRoutes);
app.use('/api/v1/admin/reports', reportRoutes);
app.use('/api/v1/admin/notifications', notificationRoutes);
app.use('/api/v1/clinical', clinicalRoutes);
app.use('/api/v1/contact', contactRoutes);
app.use(notFound);
app.use(errorHandler);

module.exports = app;
