import { useState } from 'react'
import { FiArrowUpRight, FiMail, FiMapPin, FiPhone } from 'react-icons/fi'
import { toast } from 'react-toastify'
import api from '../../services/api'

const initialForm = { name: '', email: '', topic: '', message: '' }
function Contact() {
  const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(false); const [errors, setErrors] = useState({})
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = async (event) => { event.preventDefault(); const nextErrors = {}; if (form.name.trim().length < 2) nextErrors.name = 'Please enter your name.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) nextErrors.email = 'Enter a valid email address.'; if (!form.topic) nextErrors.topic = 'Please choose a topic.'; if (form.message.trim().length < 10) nextErrors.message = 'Please provide at least 10 characters.'; setErrors(nextErrors); if (Object.keys(nextErrors).length) return; setLoading(true); try { const { data } = await api.post('/contact', form); toast.success(data.message); setForm(initialForm); } catch (error) { toast.error(error.response?.data?.message || 'Unable to send your message. Please try again.'); } finally { setLoading(false); } }
  return <section className="contact-section" id="contact"><div className="shell contact-card"><div className="contact-intro"><p className="section-kicker">LET’S CONNECT</p><h2>Ready to make care flow better?</h2><p>Tell us a little about your organization and we’ll show you what a more connected hospital can feel like.</p><div className="contact-details"><a href="tel:+919876543210"><FiPhone /><span><small>Call us</small>+91 98765 43210</span></a><a href="mailto:hello@medisphere.health"><FiMail /><span><small>Email us</small>hello@medisphere.health</span></a><span><FiMapPin /><span><small>Visit us</small>Ahmedabad, Gujarat, India</span></span></div></div><form className="contact-form" onSubmit={submit} noValidate><div className="form-row"><label>Full name<input name="name" value={form.name} onChange={change} placeholder="Your name" aria-invalid={Boolean(errors.name)} />{errors.name && <small>{errors.name}</small>}</label><label>Work email<input name="email" value={form.email} onChange={change} type="email" placeholder="you@hospital.com" aria-invalid={Boolean(errors.email)} />{errors.email && <small>{errors.email}</small>}</label></div><label>How can we help?<select name="topic" value={form.topic} onChange={change} aria-invalid={Boolean(errors.topic)}><option value="" disabled>Select a topic</option><option>Request a demo</option><option>Product question</option><option>Partnership</option></select>{errors.topic && <small>{errors.topic}</small>}</label><label>Message<textarea name="message" value={form.message} onChange={change} rows="4" placeholder="Tell us about your hospital..." aria-invalid={Boolean(errors.message)} />{errors.message && <small>{errors.message}</small>}</label><button className="button" type="submit" disabled={loading}>{loading ? 'Sending message…' : <>Send message <FiArrowUpRight /></>}</button></form></div><div className="map-placeholder"><div><FiMapPin /><strong>MediSphere</strong><span>Ahmedabad, India</span></div><i /><i /><i /></div></section>
}
export default Contact
